### ISSUE TITLE
ModuleNotFoundError: No module named 'pychromepdf'

### ISSUE THREAD

**Issue by keeyong** [navin-mohan/pychromepdf#1]
I installed the module in Python3:

```
pip3 install pychromepdf
```

And then ran a test code in the README.md but got the module not found error:

```
Traceback (most recent call last):
  File "testPDF.py", line 1, in <module>
    from pychromepdf import ChromePDF
ModuleNotFoundError: No module named 'pychromepdf'
```

I am running this on Mac. Any idea? Thanks!

**Comment by navin-mohan** [comment]
You're probably using the default python 2 executable.
