### ISSUE TITLE
win10 support?

### ISSUE THREAD

**Issue by fakeProgrammer0** [navin-mohan/pychromepdf#10]
Is it supported by win10? I use the path `C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe `, but it doesn't work.

**Comment by navin-mohan** [comment]
No. It is not supported on Windows as of now.

**Comment by fakeProgrammer0** [comment]
> No. It is not supported on Windows as of now.

Thanks for your reply.
